# Generated by Django 5.0.6 on 2024-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0002_alter_tovar_options_tovar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(height_field=600, null=True, upload_to='tovarIMG', width_field=600),
        ),
    ]
