# Generated by Django 5.0.6 on 2024-07-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0003_tags_tovar_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='AppBase.tags'),
        ),
    ]
