# Generated by Django 5.0.6 on 2024-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0004_alter_tovar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(null=True, upload_to='tovarIMG'),
        ),
    ]
