# Generated by Django 5.0.6 on 2024-07-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBase', '0006_response_user_tovar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
    ]
